name: specchio

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pytest pytest-cov flake8 coveralls
          pip install -e .
      - name: Test with flake8
        run: |
          flake8 tests specchio
      - name: Test with pytest
        run: |
          pytest tests --cov specchio --cov-report term --cov-report html
      # TODO set token
      # - name: Report coverage
      #   run: |
      #     coveralls
